pipeline {
    agent any
    tools {
        maven "M3"
        jdk "Java17"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/yme754/angular-flight-booking-system'
            }
        }
        stage('Build Microservices') {
            steps {
                script {
                    def services = ['booking-service', 'flight-service', 'flight-api-gateway', 'flight-service-registery', 'flight-security-service', 'flight-config-server', 'flight-email-service']
                    services.each { svc ->
                        dir("backend/${svc}") {
                            sh "mvn clean package -DskipTests"
                        }
                    }
                }
            }
        }
        stage('Build Docker Images') {
            steps {
                script {
                    def services = ['booking-service', 'flight-service', 'flight-api-gateway', 'flight-service-registery', 'flight-security-service', 'flight-config-server', 'flight-email-service']
                    services.each { svc ->
                        dir("backend/${svc}") {
                            sh "docker build -t ${svc}:latest ."
                        }
                    }
                }
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                sh "docker-compose up -d"
            }
        }
    }
}
